metrics:
- name: "github_pr_list"
  help: "list of github PRs for kubernetes/kubernetes"
  bearer: 
    endpoint: http://localhost:3000/get-token
  endpoint: https://api.github.com/graphql
  query: |
    {
      repository(owner: "gregoryguillou", name: "oops") {
        pullRequests(states: OPEN, first: 100) {
          nodes {
            title
            isDraft
            url
          }
        }
      }
    }
  list: repository.pullRequests.nodes
  labels:
  - name: title
    value: title
  - name: url
    value: url
  value: 1
