---
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: Opaque
stringData:
  client_secret: "0xxx"
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEog...
    -----END RSA PRIVATE KEY-----
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: github-prometheus
data:
  app_id: 100000
  client_id: Iv1.client_id
  config.yml: |
    metrics:
    - name: "github_pr_list"
      help: "list of github PRs for impakt-io/diamond"
      bearer:
        endpoint: http://localhost:3000/get-token
      endpoint: https://api.github.com/graphql
      query: |
        {
          repository(owner: "impakt-io", name: "diamond") {
            pullRequests(states: OPEN, first: 100) {
              nodes {
                title
                isDraft
                url
              }
            }
          }
        }
      list: repository.pullRequests.nodes
      labels:
      - name: title
        value: title
      - name: url
        value: url
      value: 1
